### ISSUE TITLE
SARF: Formatting of the questions 

### ISSUE THREAD

**Issue by bjlarkin** [BlueCodeSystems/nacmis#107]
Hi Blue Code,

For all the questions asked in the SARF, we would recommend the following: 

1. Standardize whether or not the questions should be all capital or normal
2. Ensure that all questions have a question mark at the end
3. Add an information button that opens a new window for the indicator description
4. Consider a color change- the contrast between blue/white and black/white of the responses make it a little difficult to look at the screen (will the color scheme be updated to NAC colors or is this the final color palette? 

Thanks! 
Akros team

**Comment by kaykabwe** [comment]
Question 2 resolved, the rest are split into other issues.
