### ISSUE TITLE
SARF: Arrange the questions on the form

### ISSUE THREAD

**Issue by NanaPietrausT** [BlueCodeSystems/nacmis#125]

**Comment by NanaPietrausT** [comment]
**Arrange the questions according to how they appear on the hard copy SARF form**. 

For example, question 24 (on the SARF paper form) is appearing as question 1 in the system
![illustration](https://user-images.githubusercontent.com/39187991/40612880-908632c0-627c-11e8-8a86-d24930a1aaa1.PNG)

**Comment by kaykabwe** [comment]
Resolved
