### ISSUE TITLE
SARF: Add gender (female and male) on question 3 

### ISSUE THREAD

**Issue by NanaPietrausT** [BlueCodeSystems/nacmis#128]
On question 3, besides requesting the overall number of teachers who received training..... Add **Female** and **Male** as well - to request the number of male and female teachers that received training 
![number of teachers](https://user-images.githubusercontent.com/39187991/40649872-2e0f494a-6332-11e8-93f4-b3520ce2b97a.PNG)

**Comment by kaykabwe** [comment]
Resolved
