### ISSUE TITLE
SARF: Add ages to question 5 

### ISSUE THREAD

**Issue by NanaPietrausT** [BlueCodeSystems/nacmis#129]
Add ages 10-14, 15-19, 20-24 and 25+ to question 5 (How many sex workers were reached with HIV prevention programmes by your organisation)
![sex workers](https://user-images.githubusercontent.com/39187991/40651118-389263ea-6335-11e8-91de-d9024d23109d.PNG)

**Comment by kaykabwe** [comment]
Resolved
