### ISSUE TITLE
Stakeholder Directory form: Changing Province, issue with Organisation District

### ISSUE THREAD

**Issue by blautenslager** [BlueCodeSystems/nacmis#141]
In the Basic Details section of the Stakeholder Directory form:
- Select an Organisation province, then select an Organisation District
- Now change the province to another province that does not use the district you selected.
- Do not change the district and save the Stakeholder Directory. 

It will let you save the Stakeholder Directory even though the selected district is not a valid district for that province.

**Comment by kaykabwe** [comment]
Resolved
