### ISSUE TITLE
Stakeholder Directory: Duplicates are not flagged for Program Activities, Funding Sources, and Target Group Prevention Messages

### ISSUE THREAD

**Issue by blautenslager** [BlueCodeSystems/nacmis#147]
For Program Activities, Funding Sources, and Target Group Prevention Messages, you can add duplicate entries. For example, I added two program activities with the same values selected for ward and program activities by geographic area and it let me save the stakeholder directory. It needs to check and remove duplicates before saving or give an error that there are duplicates.

**Comment by kaykabwe** [comment]
Resolved
