### ISSUE TITLE
Collapse Stakeholder Directory filter options?

### ISSUE THREAD

**Issue by blautenslager** [BlueCodeSystems/nacmis#150]
For the Stakeholder Directory filters, can the filters be collapsed so you don't see all the options unless you want to filter on that field? It would make it easier to see all the filters available if you didn't have to scroll down passed all the options for the first filter. Or make them drop down lists instead of just displaying a list of all possible options.

**Comment by AndreLesa** [comment]
Won't be possible with the platform in use.
