### ISSUE TITLE
Stakeholder directory: WHICH SOURCES OF INFORMATION DOES YOUR ORGANISATION UTILIZE TO INFORM HIV PROGRAMMING AND DECISION MAKING? 

### ISSUE THREAD

**Issue by bjlarkin** [BlueCodeSystems/nacmis#188]
For question: WHICH SOURCES OF INFORMATION DOES YOUR ORGANISATION UTILIZE TO INFORM HIV PROGRAMMING AND DECISION MAKING? 

Please change answer format to a multiple select answer with a fill-in-the-blank 'other' option.

**Comment by kaykabwe** [comment]
Resolved
