### ISSUE TITLE
Stakeholder directory: Program Activities- ward 

### ISSUE THREAD

**Issue by bjlarkin** [BlueCodeSystems/nacmis#191]
Please confirm that the ward drop down filters by the selected Province > District selected at the top of the form.

**Comment by tobiasmakai** [comment]
Hi @bjlarkin,
It should be able to filter down to Ward now. Please test it out again.

**Comment by bjlarkin** [comment]
@tobiasmakai - Lusaka wards look better, but some wards are not showing up for districts.

Examples of no wards in Lusaka Province: Luangwa, Chirundu, Chongwe 

Additionally, there are duplicate wards showing up in the drop down for Lusaka district (example: John Howard, Independence). Could the lists be filtered alphabetically & duplicates removed?

**Comment by tobiasmakai** [comment]
Noted with thanks @bjlarkin the duplicates will be removed  as for the districts missing wards, we have not yet finished populating wards for all districts.

**Comment by AndreLesa** [comment]
Closed - in reference to the work taking place under  https://github.com/BlueCodeSystems/nacmis/issues/163
