### ISSUE TITLE
Question 24 on SARF is not correct in the system 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#212]
Question 24 on SARF is not correct in the system

**Comment by kaykabwe** [comment]
24. What types of care and support does your organisation provide? (select all that apply)
thats the same question on paper form and list is a multi- select.

**Comment by kaykabwe** [comment]
no problem here. organisation spelling is the agreed on spelling according to issue #105. Update paper version spellings.
