### ISSUE TITLE
Validation: SARF submission process. Align the validation process according to the following process and validation user roles

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/nacmis#220]
![validation_process](https://user-images.githubusercontent.com/25362528/41462850-844ac78e-7094-11e8-951b-82f3816bc4ce.PNG)
![validation_process_notes](https://user-images.githubusercontent.com/25362528/41462855-8d433c90-7094-11e8-9a10-b578c191548d.PNG)

**Comment by kaykabwe** [comment]
Resolved
