### ISSUE TITLE
Activity report form: Heading colors 

### ISSUE THREAD

**Issue by bjlarkin** [BlueCodeSystems/nacmis#225]
Change the color of the section headers to show the difference between a question and a section header. 
<img width="1136" alt="screen shot 2018-06-18 at 10 26 14" src="https://user-images.githubusercontent.com/38097551/41526169-a755b242-72e3-11e8-9a67-d60da66e0f0e.png">

**Comment by kaykabwe** [comment]
Resolved. But suggestions for official colors would be helpful
