### ISSUE TITLE
Creating a space between age categories for all questions that have two lines of age categories 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#226]
It looks a bit tight and slightly confusing. Can we add a space between for all of these questions. Please see attachment. 
<img width="1164" alt="screen shot 2018-06-18 at 11 22 47 am" src="https://user-images.githubusercontent.com/38062748/41528357-2639aafe-72ea-11e8-9508-c904cec72fe5.png">

**Comment by kaykabwe** [comment]
issue depends on view port  (or adjusts with screen). to discuss.

**Comment by AndreLesa** [comment]
Happy to discuss, but this look is based on screen resolution. Looks fine for most computers tested.
