### ISSUE TITLE
On SARF change final "SAVE" to "SUBMIT" 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#228]
On SARF change final "SAVE" to "SUBMIT" 
<img width="1216" alt="screen shot 2018-06-18 at 11 35 00 am" src="https://user-images.githubusercontent.com/38062748/41528924-caccb790-72eb-11e8-9e0d-34c9cefb0678.png">

**Comment by kaykabwe** [comment]
Resolved
