### ISSUE TITLE
Change labels from "Validation status" to  "Validation Status",  "Daca initials" to "DACA Initials" etc

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/nacmis#241]
Look for similar labels and update accordingly in readiness for screenshots for the user manual development
![gitshot1](https://user-images.githubusercontent.com/25362528/41647093-b4c7a460-7475-11e8-8611-695af1fcbd32.PNG)

**Comment by kaykabwe** [comment]
Resolved
