### ISSUE TITLE
Stakeholder permissions- Stakeholder directory 

### ISSUE THREAD

**Issue by bjlarkin** [BlueCodeSystems/nacmis#245]
Under the Stakeholder permissions, remove the ability to see the Filter field for Stakeholder Directory landing page. 

Stakeholders should only be able to see their own directory and therefore the filter feature might be unnecessary and potentially confusing for the stakeholder. @AndreLesa @tobiasmakai - thoughts?

**Comment by AndreLesa** [comment]
Happy to discuss how much of a priority it is - then we can reopen. But otherwise a hustle to customize the filter based on person logged in.
