### ISSUE TITLE
Priority: Data pulling from wrong source in data visual, needs to be changed 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#279]
<img width="421" alt="screen shot 2018-07-11 at 8 23 40 am" src="https://user-images.githubusercontent.com/38062748/42554102-da98b50c-84e3-11e8-9502-27ec0e6b62cb.png">

This visual is pulling from the wrong place. This visual should be showing the types of mobile workers that are targeted with HIV programmes. It is pulling from organization type. 

When I tried to change the source in superset it was not an option.

**Comment by AndreLesa** [comment]
Fixed
