### ISSUE TITLE
Removing count on the bottom of all charts 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#280]
<img width="399" alt="screen shot 2018-07-11 at 8 26 53 am" src="https://user-images.githubusercontent.com/38062748/42554251-71be5a0e-84e4-11e8-848d-e2018ab07eeb.png">

The count on the bottom line is confusing, I tried on different screens to see if it would change. But the figure is looking like 745,740 and not two separate numbers. I tried to remove this from the charts, but was unable to. This feature makes the data confusing, please remove from all charts.

**Comment by kaykabwe** [comment]
Particular chart is now showing as a big number. Resolved.
