### ISSUE TITLE
Condom distribution points pulling from wrong data source 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#283]
<img width="1095" alt="screen shot 2018-07-11 at 8 47 17 am" src="https://user-images.githubusercontent.com/38062748/42554971-179002f0-84e7-11e8-989f-d2352ac586a6.png">

This should be a big number of total number of distribution points. I tried to change this to a big number but was unsuccessful.

**Comment by AndreLesa** [comment]
Fixed - using province and districts for breakdown
