### ISSUE TITLE
Priority: Dashboard filters need to be updated for all dashboards 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#284]
The dashboard filters should be updated to reflect the list on the visualization document on the team drive and shown below
<img width="327" alt="screen shot 2018-07-11 at 9 09 19 am" src="https://user-images.githubusercontent.com/38062748/42555943-43885864-84ea-11e8-9dfa-0b100c8ecdd5.png">
: 

Dashboard Filters:
SARF/ Key population: Preset filters: 
Automatic Map: HMIS HIV Incidence/ Prevalence/ and total population
Female/male
District/ Province
Age disaggregation categories
Time stamp

Stakeholder Directory preset filters:
Automatic Map: HMIS HIV Incidence/ Prevalence/ and total population
Classification type (organization)
Target group
Geographic activities
Province/ district/ ward
By organization (show breakdown of who is working where and doing what) 

Internal monitoring filters: 
Time stamp

**Comment by Mellorison** [comment]
Hello. So The following is the status of the Filters:
- Female/male : Can not be implemented.
- Age Disaggregation can not be implemented
- Timestamp : Implemented
- Classification type(organization) : Implemented on the Map
- Target Group : Implemented
- Geographic activities : Implemented on Map
- Province/District/Ward By  organization (show breakdown of who is working where and doing what) : Implemented on Map
