### ISSUE TITLE
Placeholder tab for Internal Monitoring Dashboard 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#285]
<img width="467" alt="screen shot 2018-07-11 at 9 12 10 am" src="https://user-images.githubusercontent.com/38062748/42556043-98429784-84ea-11e8-9115-d08713603839.png">

Please create a tab for the other dashboard on Internal Monitoring

**Comment by kaykabwe** [comment]
Resolved on #264
