### ISSUE TITLE
Dashboard filter should pre-populate districts and show only districts in that province 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#288]
<img width="335" alt="screen shot 2018-07-11 at 12 21 26 pm" src="https://user-images.githubusercontent.com/38062748/42565887-04643f70-8505-11e8-858a-dab15b9c2392.png">

If I select Copperbelt, I should only see districts in Copperbelt to select, right now I am seeing districts outside of CB.

**Comment by Mellorison** [comment]
Resolved
