### ISSUE TITLE
Priority: When I filter, I should only see data for that filter on my chart 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#289]
<img width="1003" alt="screen shot 2018-07-11 at 12 26 56 pm" src="https://user-images.githubusercontent.com/38062748/42566115-c7b46b1c-8505-11e8-8697-e303c7fbae45.png">

When I am currently using the filter, it still shows data outside of that filter as seen in this example.

**Comment by AndreLesa** [comment]
Fixed for the example given in the error  @hallix  double check each of the other charts - especially the totals (Big round numbers) Seems we are not pulling in the filtering information correctly for those. @zephyrfalcon kindly check the last added view at the bottom of views.sql to make sure it also pulls in the activity report form.

**Comment by zephyrfalcon** [comment]
@AndreLesa I updated the view to include the fields of the activity report view, and fixed a problem with the way it was joined. When you join so many tables, it is hard to tell all the different IDs apart... :(

**Comment by AndreLesa** [comment]
Thanks Hans - merged your pull request. 

Adding a few more issues where we have a similar situation.

**Comment by hallix** [comment]
@eefronson the issue seems to be resolved.

**Comment by AndreLesa** [comment]
Just 1 more chart outstanding:
https://nacmis-data.bluecodeltd.com/superset/explore/?r=5

Looks like the table is not joining to the stakeholder details which have the necessary dimensions to filter by.
