### ISSUE TITLE
Stakeholder directory dashboard unclear what this is supposed to show 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#293]
Please see attached 
<img width="509" alt="screen shot 2018-07-13 at 12 24 39 pm" src="https://user-images.githubusercontent.com/38062748/42686979-dd934fe6-8697-11e8-84c6-853619cefabe.png">

**Comment by AndreLesa** [comment]
It's just a placeholder for the map X people supported. A better visual has been put in it's place.
