### ISSUE TITLE
Can we remove the ___  on the the filters 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#298]
Can it just say Province, District ---can we remove all the underscores for the filters on the various Dashboards 
<img width="227" alt="screen shot 2018-07-16 at 11 41 42 am" src="https://user-images.githubusercontent.com/38062748/42752194-6d6686a4-88ed-11e8-9f16-4b0e18f23d73.png">

**Comment by kaykabwe** [comment]
Feature part of superset. Not changeable
