### ISSUE TITLE
Stakeholder directory: The dropdown list on Target Group under the "Target Group Prevention Messages" must only include target groups listed under 'Organization Classification'

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/nacmis#31]
- On organization classification the stakeholder will have already entered a list of target groups 
![gitshot2](https://user-images.githubusercontent.com/25362528/38416483-25004ce4-3995-11e8-9316-c4a9adce9590.PNG)

- Only the target groups populated earlier must appear in the dropdown list here
![gitshot3](https://user-images.githubusercontent.com/25362528/38416705-e5508ba8-3995-11e8-86dc-6f60c91adf27.PNG)
to avoid the repeat process

**Comment by AndreLesa** [comment]
Use the same django-select 2 as we have in issue #62

**Comment by kaykabwe** [comment]
Solved
