### ISSUE TITLE
Errors on loading views.sql

### ISSUE THREAD

**Issue by kaykabwe** [BlueCodeSystems/nacmis#310]
See the screen shot below:
![screenshot from 2018-07-18 16-24-10](https://user-images.githubusercontent.com/33322655/42887823-195b25d6-8aa7-11e8-8053-6b56f6ad06b6.png)

**Comment by kaykabwe** [comment]
@zephyrfalcon The tables from the stored procedures are not created by the storedprocs.sql .

**Comment by zephyrfalcon** [comment]
@kaykabwe I am guessing some changes were made to the database? Problem is, I don't have the latest version because the migrations don't work for me. I'm getting this:

```
$ python manage.py migrate
  Applying data_entry.0002_otherquestion_sources_of_information...Traceback (most recent call last):
  File "/Users/hans/venv/nacmis/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "data_entry_sourcesofinformation" does not exist
```

I will see if I can run a specific migration file, but this is probably not ideal.

/cc @AndreLesa
