### ISSUE TITLE
DACA user permissions bug: some SARF questions not appearing 

### ISSUE THREAD

**Issue by bjlarkin** [BlueCodeSystems/nacmis#313]
During Master Class last week, users could not see specific questions in the SARF that had been edited by the stakeholder. The SARF simply skipped the edited question. Example attached.

Example details: (question 21 is skipped)
<img width="909" alt="screen shot 2018-07-19 at 11 03 42" src="https://user-images.githubusercontent.com/38097551/42932836-a1608eca-8b43-11e8-9bf2-1e2ed4bf5de5.png">

User: DACA_kitwe
SARF: Z-CHPP - Kitwe district - Copperbelt province

**Comment by AndreLesa** [comment]
Resolved and tested with:
User: DACA_kitwe
SARF: Z-CHPP - Kitwe district - Copperbelt province
