### ISSUE TITLE
PITMEO user permission update: Add view only of DACA validation box

### ISSUE THREAD

**Issue by bjlarkin** [BlueCodeSystems/nacmis#315]
PITMEO cannot see if validation has been completed by the DACA or the notes the DACA has written. This should be updated so that they have a read-only view of the DACA’s approval box.

**Comment by AndreLesa** [comment]
![image](https://user-images.githubusercontent.com/3635843/43133295-a2673086-8f3e-11e8-98bf-6ed8c0f75bac.png)
Resolved.
