### ISSUE TITLE
Missing SARF form section headers 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#322]
<img width="1238" alt="screen shot 2018-07-23 at 10 10 17 am" src="https://user-images.githubusercontent.com/38062748/43064989-c54ff418-8e60-11e8-8710-e8017a058664.png">

The section headers for HIV activity impact areas are missing. i.e Social Behavior Change Communication; Social behavior change communication for key populations; condom programming; etc. 

The online form should mirror the paper form as closely as possible in order for ease of submission for stakeholders. 
<img width="488" alt="screen shot 2018-07-23 at 10 13 42 am" src="https://user-images.githubusercontent.com/38062748/43065114-1b40db12-8e61-11e8-8017-6a86c26006f4.png">

**Comment by kaykabwe** [comment]
Resolved.
