### ISSUE TITLE
Key pops dashboard age filter, ages not in the correct order 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#326]
<img width="339" alt="screen shot 2018-07-23 at 10 43 10 am" src="https://user-images.githubusercontent.com/38062748/43066560-46ed21cc-8e65-11e8-91d1-d768f486e049.png">

Can we also remove the underscore "_" from all

**Comment by AndreLesa** [comment]
Closed with reference to #327
