### ISSUE TITLE
Visuals with age categories only showing low end of the age category and not the entire age bracket 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#327]
<img width="340" alt="screen shot 2018-07-23 at 10 46 38 am" src="https://user-images.githubusercontent.com/38062748/43066758-c44afe50-8e65-11e8-9425-a93d19eafa85.png">

In the example, you can see it is only showing "15" instead of "15-19" this appears this way for all age categories.

**Comment by Mellorison** [comment]
![vulnerable](https://user-images.githubusercontent.com/41048336/43428486-05c1d7bc-944e-11e8-991f-9174524a799f.PNG)
This is how the age category/age bracket is appearing on my Dashboard. Is it still appearing with only the low end of the age category on yours?

**Comment by Mellorison** [comment]
Resoved
