### ISSUE TITLE
Wrong Page display

### ISSUE THREAD

**Issue by J8mes22** [BlueCodeSystems/nacmis#350]
**So when you logging with any user, the system is loading straight to the admin page as displayed below.**

![image](https://user-images.githubusercontent.com/34535671/43462556-b30efcaa-94d6-11e8-8b17-40499ff30281.png)

**Please make it so the user first sees the actual home page(picture below) when they are logged in. Make the home page be the landing page at Login**

![image](https://user-images.githubusercontent.com/34535671/43462836-7277b96a-94d7-11e8-91bc-b14f6702c0a6.png)
Thanks.

**Comment by AndreLesa** [comment]
@J8mes22 When you login from the homepage, you are redirected to the homepage, if you login after clicking any of the dashboard links, you will be redirected to the link you wanted to go to.

If you are already on the admin site when you click login, you will be redirected to the admin site.
