### ISSUE TITLE
Text on NACMIS Landing page 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#352]
Welcome to the National HIV/AIDS/STI/TB Council Management Information System (NACMIS)
NACMIS provides a holistic picture for the HIV and AIDS multisectoral response in Zambia targeting not only decision-makers across all levels but also the public. This is a platform that officially triangulates the National HIV and AIDS programmatic data with social-determinants, behavior change and clinical data sets in line with the National HIV and AIDS Strategic Framework 2017-2021 in order to develop a culture of HIV and AIDS prevention data for decision-making at all levels of government and partner interventions.
Thank you for partnering in the response to HIV and AIDS.

**Comment by kaykabwe** [comment]
Resolved
