### ISSUE TITLE
Confirm IP Address

### ISSUE THREAD

**Issue by Kamumaji** [BlueCodeSystems/nacmis#356]
From: Kapampa Michael Mulenga [mailto:kapampa.mulenga@zamnet.zm] 
Sent: Monday, July 30, 2018 1:34 PM
To: 'Kamumaji Chitundu'; 'noc@zamnet.zm'
Subject: RE: POINTING OF DOMAIN
 
Kindly confirm IP address of the webserver we have 54.89.75.33
 
regards
 
Kapampa M Mulenga | Network Specialist |Office: +260 211 227430 |Mobile: +260 978 953591 | Skype ID: kapampam | Comesa Center | Ben Bella Road | P.O Box 38299 |Lusaka, ZAMBIA

**Comment by AndreLesa** [comment]
Confirmed - that's the address.
