### ISSUE TITLE
Graph on condom distribution 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#383]
The  Graph showing condom distribution is not available  .
we would like to have a Bar graph of  Number of condoms distributed by male  & female condoms  showing a trend of a number of selected  reporting quarters

**Comment by Mellorison** [comment]
How is this? ![graph on condom distribution](https://user-images.githubusercontent.com/41048336/44347794-4e3e1880-a488-11e8-814e-bd77dc4581d9.PNG)

**Comment by nsoko** [comment]
the Graph is ok but I think a stacked bar graph would be better

**Comment by nsoko** [comment]
Thats better great work

**Comment by Mellorison** [comment]
Resolved
