### ISSUE TITLE
Hiding other organisations  when logged in as Stakeholder

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#393]
it would be helpful  once  a user is logged in as  stakeholder they should only be able to see the organisation which is linked to there SARF.
currently  a stakeholder is able to see all the stakeholders even from other districts

**Comment by AndreLesa** [comment]
This is the case at the moment. Most likely permissions were not assigned properly to that stakeholder. See screenshot attached when am logged in as stakeholder, I can only see my own organization.

Which stakeholder was it?

![image](https://user-images.githubusercontent.com/3635843/44589153-0dac0b00-a7b8-11e8-8c25-b670494b81f9.png)
