### ISSUE TITLE
Is there a way to scroll the DACA list without having to click on the icon to go down

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#395]
I know there is a search feature, but if someone just wants to scroll down without clicking is it possible? 
<img width="1210" alt="screen shot 2018-08-24 at 3 20 46 pm" src="https://user-images.githubusercontent.com/38062748/44603673-6b892480-a7b1-11e8-8539-bc05f2e5ddf1.png">

**Comment by kaykabwe** [comment]
Resolved. Waiting  for review.
