### ISSUE TITLE
Upload Stakeholder Directory Definitions to resource tab

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#400]
I was just informed their are definitions for the stakeholder directory..this should be uploaded under the resources tab 

Under Stakeholder Directory Definitions: 
This document explains each Stakeholder Directory indicator, the correct data source, and is intended to ensure accuracy in reporting. If you still have questions about indicators and how to report you should contact your DACA.

**Comment by AndreLesa** [comment]
For this, the idea was that NAC uploads the files to a relevant Google drive and shares the links with us. 

That will make it easier to update the docs without changing the website.

Hence what we need for the definitions will be the file links. Files should be hosted on NAC side.

**Comment by AndreLesa** [comment]
@nsoko  Kindly upload the relevant files to Google docs and set permissions to public, then give us the links.

**Comment by kaykabwe** [comment]
Related to issue #399

**Comment by Mellorison** [comment]
Resolved.
