### ISSUE TITLE
Dashboard names have not been changed 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#404]
Dashboard names have not been changed...the PACA/PITMEO should be combined to Provincial Dashboard and DACA to District  

and should ordered correctly. Internal monitoring should appear last. 

<img width="277" alt="screen shot 2018-08-24 at 3 48 39 pm" src="https://user-images.githubusercontent.com/38062748/44604849-41d1fc80-a7b5-11e8-9be3-8be7be8a3f44.png">

**Comment by kaykabwe** [comment]
Resolved
