### ISSUE TITLE
Key pops dashboard still have GBV visuals and condom distribution- these need to be moved to the SARF dashboard

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#406]
Key pops dashboard still have GBV visuals and condom distribution- these need to be moved to the SARF dashboard

**Comment by AndreLesa** [comment]
This would be a good opportunity for @nsoko to practice on the dashboards as the dashboards training covered that.

Happy to help if needed.

**Comment by Mellorison** [comment]
Resolved.
