### ISSUE TITLE
PITMEO/Provincial user accounts 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#417]
I suggest that when one is logged in as a PITMEO /Provincial  they should only be able to view the stakeholder directories of their Respective  province  eg currently if you are logged in as PITMEO Luapula you are able to view directories of southern Province

**Comment by kaykabwe** [comment]
Thanks. Please show a screen shot. Which user are you using?

**Comment by nsoko** [comment]
![image](https://user-images.githubusercontent.com/38098694/44708414-683eb300-aaa7-11e8-85dd-f53cc9c9568e.png)

**Comment by kaykabwe** [comment]
ok. Looking into it.

**Comment by kaykabwe** [comment]
@nsoko Issue resolved. You can test again.
