### ISSUE TITLE
disappearance of Milenge Stakeholder directories 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#418]
stakeholder directories for Milenge district have disappeared  despite  being entered earlier  even the recent actions trail shows that they have been entered. how can this be addressed

**Comment by kaykabwe** [comment]
There was a ward "Milengi" instead of "Milenge". Then a Milenge was added. Those Stakeholder directories that were under "Milengi" and were causing confusion, have been deleted with that particular ward name. The way forward is to re-enter the ward name. If it happens again let us know.
