### ISSUE TITLE
section 4 of Stakeholder directories  Program activities 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#420]
the List of program activities should be 

1. Elimination   of  Mother-to-Child Transmission   (eMTCT)
2..Condom   Programming
3. .Voluntary   Medical male Male Circumcision (VMMC)
4.  HIV Testing   Services
5.  Social and   Behaviour Change Communication
6.  HIV/TB Co-   Infection treatment
7. Provision of   Pre Exposure Prophylaxis (PrEP)
8. STI Screening   and Treatment
9. Treatment   Optimization
10. Treatment of   HIV/AIDS/STIs and TB
12. Gender   Equality, equity & empowerment
13. , Laws,   and Human Rights
14. Elimination of   Stigma and Discrimination
15. Resource   Mobilisation & sustainable financing
16. Positive   Health Dignity and Prevention
18. Post-Exposure   Prophylaxis (PEP)

20. Viral   Hepatitis Infection
21. Blood Safety
22. Psychosocial   Support for PLHIV
23. Synergies with   other Development Sectors
24.  Education   Sector
25.   Adolescent   and Young People
26. HIV and AIDS   Integration and Systems Strengthening
28. Integration   Of HIV/AIDS, Sexual Reproductive Health and Other Services
30. Health   Systems Strengthening
31. Community Systems Strengthening
32. Social   Protection
33. Nutrition   and Food Security
34. Poverty   Alleviation and Livelihoods
35. Mainstreaming   HIV Into Capital Projects
36. HIV/AIDS   Workplace Policies and Practices

**Comment by kaykabwe** [comment]
@nsoko This is for the section under program activities on stakeholder directory. As a super user you can add, edit and by navigating as follows. on admin page, under data entry click "support field". Can rename to something more visible. Is "program activities" a better name?

**Comment by kaykabwe** [comment]
@nsoko just wait. Adding another other list.

**Comment by kaykabwe** [comment]
@nsoko  issue resolved. Log in as superuser and add the above options. This way you get add more. Also all stakeholder directories will have to be edited to have values in the above list after entering.

**Comment by nsoko** [comment]
kaykabwe  noted and executed
