### ISSUE TITLE
stakeholder permissions iam logged in as a stakeholder but iam seeing other stakeholders when submitting SARF

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#422]
![image](https://user-images.githubusercontent.com/38098694/44722182-95ea2300-aacc-11e8-8474-509e2500eb9f.png)
stakeholder permissions iam logged in as a stakeholder but iam seeing other stakeholders when submitting SARF

**Comment by AndreLesa** [comment]
Hi Mr Soko, kindly provide the username for any permissions related issue.

**Comment by kaykabwe** [comment]
Resolved
