### ISSUE TITLE
Stakeholder Not Able to see submitted SARF

### ISSUE THREAD

**Issue by Kamumaji** [BlueCodeSystems/nacmis#423]
Hi Team,

We have noticed that once a stakeholder submits a SARF, they are not able to see the submitted SARF, however the DACA will be able to see it.

**Comment by kaykabwe** [comment]
Will look into it. Which Stakeholder user are you using?

**Comment by kaykabwe** [comment]
Will look into it. Which Stakeholder user are you using?

**Comment by kaykabwe** [comment]
@Kamumaji am not seeing the error you are mentioning. Maybe note down the steps you are taking so that we can access the issue better. for now am closing issue.
