### ISSUE TITLE
System is allowing SARFs from the same organisation & same reporting period to be entered more than once

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#427]
System is allowing SARFs from the same organisation & same reporting period to be entered more than once.
This is the case under dacamansa & dacambala  can the system be improved upon to  only allow one SARF per organisation per reporting Quarter

**Comment by kaykabwe** [comment]
Will look into this.

**Comment by AndreLesa** [comment]
Resolved
