### ISSUE TITLE
Quarters Been Reported

### ISSUE THREAD

**Issue by Kamumaji** [BlueCodeSystems/nacmis#436]
Hi Team,
Admin..Also make corrections on drop down list for quarters 3 and 4 when entering sarfs
Quarter 1 Jan -March
Quarter 2 April - June
Quarter 3 July - September
Quarter
![quaterly months](https://user-images.githubusercontent.com/40383901/45296776-680cd180-b503-11e8-95e4-9afba33a135a.JPG)
 4 October - December

**Comment by nsoko** [comment]
Any Progress  on this issue 
Jan- Mar
Apr-Jun
Jul-Sept
Oct-Dec

**Comment by kaykabwe** [comment]
resolved
