### ISSUE TITLE
Error Handling  Mechanisim when creating users

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#456]
we need to build some error Handling Messages  when certain steps are not done by users 
example when a user has not completed  a user profile  an error message  appears  with codes which discourages the user 
I would prefer a message comes eg " **Please complete the User profile by  selecting National organisation & stakeholder  "**
![image](https://user-images.githubusercontent.com/38098694/46139830-d82f8d00-c24f-11e8-8d7d-ac0b57bba6f0.png)

**Comment by kaykabwe** [comment]
okay. on it

**Comment by kaykabwe** [comment]
Resolved

**Comment by nsoko** [comment]
Great work thanks
