### ISSUE TITLE
order in which age groups are appearing  On Graphs 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#457]
The graphs Age group needs to  appear in an ordered manner starting with Lower Age  group to the Higher age Group eg 10-14 15-19  20-24  25-29 30-35  35+
  this should be the same to all graphs 
![image](https://user-images.githubusercontent.com/38098694/46279412-4da99f00-c569-11e8-8b15-d407c5751a18.png)

**Comment by kaykabwe** [comment]
@nsoko superset arranges histograms by value. Attempts have been made to correct this. and the only thing that we could do is to comment this on their developers forums to add this feature in future superset updates.
