### ISSUE TITLE
Move table from Stakeholder dashboard to Internal Monitoring dashboard. Also change label/title from "SARF DATA" to Stakeholder Data

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/nacmis#461]
![national hiv aids sti tb council management information system](https://user-images.githubusercontent.com/25362528/46403984-436fd800-c704-11e8-8501-5c2163054d2a.png)

**Comment by tobiasmakai** [comment]
The fields to only include; Organisation, Key Contact Name, Position, Email Address and Phone#

**Comment by kaykabwe** [comment]
Resolved
