### ISSUE TITLE
All dashboard filters should be prefixed to quarterly not "last week" as the time range

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#470]
All dashboard filters should be prefixed to quarterly not "last week" as the time range
<img width="538" alt="screen shot 2018-10-05 at 10 18 08 am" src="https://user-images.githubusercontent.com/38062748/46524128-1a785000-c888-11e8-93ee-151ff1564d05.png">

**Comment by Mellorison** [comment]
![filter time range](https://user-images.githubusercontent.com/41048336/46525149-602e1c00-c87a-11e8-81c0-603ad7722d65.PNG)
We may risk some visualizations returning/displaying No Data if the Filter Time range is prefixed to "quarterly".  You can, however, actually pick a time range of your choice by clicking the grey "Time range" button with the "Last week" text label, depending on the time range of the data you would like to view. Simply click it and select a time range of your choice.
