### ISSUE TITLE
Stakeholder dashboard: filter says "SARF filter" also the only filters are only for province and district- missing a number of filters

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#472]
<img width="571" alt="screen shot 2018-10-05 at 10 24 13 am" src="https://user-images.githubusercontent.com/38062748/46524374-ec474000-c888-11e8-9934-b8656e69cdab.png">

Filter should not say SARF filter- but just Filter- it is confusing as this is the stakeholder dashboard

Please remove the _ from district_name and province_name

Also missing FILTERS as seen in attachment and in visualization document 
<img width="599" alt="screen shot 2018-10-05 at 10 26 14 am" src="https://user-images.githubusercontent.com/38062748/46524426-1e58a200-c889-11e8-9746-3201ea6c591e.png">

**Comment by Mellorison** [comment]
The following is the status of the Filters:
- Female/male : Can not be implemented.
- Age Disaggregation can not be implemented
- Timestamp : Implemented
- Classification type(organization) : Implemented on the Map
- Target Group : Implemented
- Geographic activities : Implemented on Map
- Province/District/Ward By  organization (show breakdown of who is working where and doing what) : Implemented on Map
