### ISSUE TITLE
Stakeholder Dashboard: Visual needs to be aggregated to combined total for national level

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#473]
<img width="391" alt="screen shot 2018-10-05 at 10 36 53 am" src="https://user-images.githubusercontent.com/38062748/46524977-aa1efe00-c88a-11e8-9dee-c29a3a02a48f.png">
 

This visual has too much information to be disaggregated by province- it should be aggregated to national level totals and then if an individual wants to use the filter to see by province and district they can. 

Additionally- we need X and Y labels on the table otherwise we don't understand what the chart is saying. I tried to add labels but it didn't work.

**Comment by Mellorison** [comment]
Resolved.
