### ISSUE TITLE
Stakeholder Directory dashboard: map should only show Zambia

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#474]
<img width="701" alt="screen shot 2018-10-05 at 10 43 10 am" src="https://user-images.githubusercontent.com/38062748/46525343-9de77080-c88b-11e8-837f-7efe78f7bbfc.png">

This visual should only be showing Zambia and not the surrounding countries.

**Comment by Mellorison** [comment]
Resolved.
