### ISSUE TITLE
Missing male/ female condom distribution visual 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#476]
<img width="470" alt="screen shot 2018-10-05 at 11 40 05 am" src="https://user-images.githubusercontent.com/38062748/46528208-7e544600-c893-11e8-85d5-6924658edc0f.png">

This visual is showing a pie chart by province- it should be showing by male condoms and female condoms. 

I looked through all the visuals created and could not find this one.

**Comment by Mellorison** [comment]
Resolved.
