### ISSUE TITLE
Confirming PrEp visual is pulling from the correct place 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#479]
<img width="1139" alt="screen shot 2018-10-05 at 12 02 54 pm" src="https://user-images.githubusercontent.com/38062748/46529409-a8f3ce00-c896-11e8-8db4-c54fac2fa9b6.png">

Is this an HMIS visual?

**Comment by Mellorison** [comment]
No. It isn't.
Issue Resolved.
