### ISSUE TITLE
Put the age ranges in 2 columns

### ISSUE THREAD

**Issue by AndreLesa** [BlueCodeSystems/nacmis#48]
![image](https://user-images.githubusercontent.com/3635843/38861818-bb4e5abe-4233-11e8-978e-82bf5ed796e5.png)

Would it be possible to put all the age groups in 2 columns as you have done below:

![image](https://user-images.githubusercontent.com/3635843/38861883-e10c6f34-4233-11e8-82c0-bce445a5dc7f.png)

**Comment by kaykabwe** [comment]
Added field-sets in inline classes
