### ISSUE TITLE
Transgender visual not showing number

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#484]
<img width="1122" alt="screen shot 2018-10-05 at 12 28 23 pm" src="https://user-images.githubusercontent.com/38062748/46530492-3127a280-c89a-11e8-8fbe-c1373f8e066e.png">

**Comment by Mellorison** [comment]
Should be showing values now. Kindly confirm.

**Comment by Mellorison** [comment]
Resolved.
