### ISSUE TITLE
Filters not functioning 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#486]
Filters for example in the Key pops dashboard are not functioning 
<img width="1142" alt="screen shot 2018-10-05 at 12 40 43 pm" src="https://user-images.githubusercontent.com/38062748/46531004-f4f54180-c89b-11e8-8217-f34d8d1d0e86.png">

On the main page without filters it shows MSM as 0 however when filtering by copperbelt it shows a huge figure

**Comment by Mellorison** [comment]
Should be resolved now. Kindly confirm from your end.
