### ISSUE TITLE
Additional visual needed on Stakeholder dashboard 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#497]
<img width="1134" alt="screen shot 2018-10-12 at 9 54 13 am" src="https://user-images.githubusercontent.com/38062748/46855788-f4f9c200-ce04-11e8-9d5f-ea2ca14a4a1f.png">

When you filter on the stakeholder dashboard you should also see the list of organizations that are doing the type of operations you are filtering for

**Comment by Mellorison** [comment]
Resolved.
