### ISSUE TITLE
Filter + visualization 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#507]
For example when you filter by Copperbelt and Ndola for this chart- you should see that you are also looking at the district of Ndola on the chart- right now it is not clear that is what you are looking at 

<img width="1057" alt="screen shot 2018-10-12 at 10 42 52 am" src="https://user-images.githubusercontent.com/38062748/46858507-b74c6780-ce0b-11e8-8d70-5c8f322c1d78.png">

**Comment by Mellorison** [comment]
Resolved.
