### ISSUE TITLE
Not understanding GBV physical violence visual 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#511]
<img width="1144" alt="screen shot 2018-10-12 at 11 00 47 am" src="https://user-images.githubusercontent.com/38062748/46859489-2cb93780-ce0e-11e8-8475-9ac95cd4455a.png">

We are having difficulty understanding this chart-- can you please explain- is this physical or sexual violence? also we need to rethink how it is formatted- currently not helpful

**Comment by Mellorison** [comment]
This is only a physical violence breakdown table.

**Comment by eefronson** [comment]
This should be a big number then - and when you filter you can see the various provinces where GBV physical violence is happening -
