### ISSUE TITLE
This data point seems incorrect -showing same data for 2 different indicators 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#519]
Showing 10 for physical and sexual -- not sure if this correct- also the number seems low 
<img width="189" alt="screen shot 2018-10-26 at 2 50 33 pm" src="https://user-images.githubusercontent.com/38062748/47567355-9c5f1480-d92e-11e8-9803-bc6021faee68.png">

**Comment by Mellorison** [comment]
Issue Rectified
