### ISSUE TITLE
Upload end user videos to the NACMIS website under resources tab

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#521]
There are 9 end user video guides in the drive folder that a final-Please upload these to the NACMIS under the resources Tab

NAC will upload the videos to YouTube seperately

**Comment by AndreLesa** [comment]
It will be best to upload them to youtube then we embed the Youtube links as videos. The experience will be tons better for the user as Youtube has infinitely more network bandwidth than we can have.

**Comment by eefronson** [comment]
@Nyewani C. Soko<mailto:nsoko@nacsec.org.zm> can you chat with Comms teams regarding the password so we can get these up on the site

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by kaykabwe** [comment]
Found the video's
