### ISSUE TITLE
Hovering filters 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#525]
When will be able test the hovering filters?

**Comment by Mellorison** [comment]
The following is the status of the Filters:
- Female/male : Can not be implemented.
- Age Disaggregation can not be implemented
- Timestamp : Implemented
- Classification type(organization) : Implemented on the Map
- Target Group : Implemented
- Geographic activities : Implemented on Map
- Province/District/Ward By  organization (show breakdown of who is working where and doing what) : Implemented on Map
