### ISSUE TITLE
Heat map of Zambia showing HIV prevalence on the landing page 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#530]
Nyewani to send provincial numbers for the heat map on the landing page showing HIV prevalence

**Comment by nsoko** [comment]
**HIV Prevalence**
       **National**    **11.6%**
Central                  13.4%
Copperbelt             14.2%
Eastern                    8.2%
Luapula                   9.3%
Lusaka                    16.1%
Muchinga                5.9%
Northern                  9.7%
North western         6.9%
Southern                  13.4%
Western                    16%
