### ISSUE TITLE
error under dacachinsali 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#531]
![image](https://user-images.githubusercontent.com/38098694/48198517-cb7b7a00-e361-11e8-8f2c-edbe669a54a1.png

this  happens  when trying  add  & view a SARF and directory  &  users 
kindly help

**Comment by nsoko** [comment]
This Error pops up even when logged in as admin

**Comment by kaykabwe** [comment]
@nsoko Working on fixing the pitmeo authentication. The site will be temporarily down.
