### ISSUE TITLE
HMIS chart should be combined - currently not correct for STI notifications and STI treatment  

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#532]
This should be a bar chart with two bars next to one another comparing 

1. Total number of STI notifications next to a second bar showing total number of those with STI notifications treated

Ensure the data is also pulling from the correct place--the phrasing of the indicators is confusing- ensure it aligns with exactly what the indicator is in HMIS
<img width="867" alt="screen shot 2018-11-09 at 10 22 57 am" src="https://user-images.githubusercontent.com/38062748/48251387-2072cb00-e40a-11e8-9a7d-6f98665da2b3.png">

**Comment by Mellorison** [comment]
Resolved.
