### ISSUE TITLE
Incorrect data visual - should be combined chart

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#533]
<img width="238" alt="screen shot 2018-11-09 at 10 31 39 am" src="https://user-images.githubusercontent.com/38062748/48251549-b27ad380-e40a-11e8-8f9c-46bfb444a766.png">

This is supposed to be a bar chart showing 1. total number of all referrals for PeP (from NACMIS) vs Total number provided PeP from HMIS

**Comment by Mellorison** [comment]
Resolved.
