### ISSUE TITLE
Knowledge of HIV prevention methods for both males and females need to pull from a different place

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#536]
Pg. 199

The chart for both should say the following for both the women and men charts: 

"Percentage of women/men who say HIV can be prevented by using a condom and limiting sexual intercourse to one uninfected partner" 

It should pull from indicator that captures both condom and limiting to one sexual partner- @nyewani can send the numbers if you don't have them.

**Comment by Mellorison** [comment]
Resolved.
