### ISSUE TITLE
Stakeholder Directory: Which year did your organization start working?

### ISSUE THREAD

**Issue by bjlarkin** [BlueCodeSystems/nacmis#54]
### Akros recommendation: 

- [x] 1.        Add to the date description for what format is requested . ie- the question should read: 'Which year did your organization start working? (YEAR-MM-DD)
- [ ] 2.        Consider only allowing for the YEAR and not include the day and month   
- [x] 3.        Create validation rules to prevent acceptance of text    
- [ ] 4.        Update error message to be more descriptive of how to correct the mistake

--

**Comment by kaykabwe** [comment]
Issue to change to year has always been the initial requirement. Work in progress. issue to be spit in several issues.
