### ISSUE TITLE
Remove bottom label from visual - also is it pulling from only one location?

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#550]
<img width="776" alt="screen shot 2018-11-15 at 11 22 54 am" src="https://user-images.githubusercontent.com/38062748/48542979-27498400-e8c9-11e8-8fae-e49493f1abc8.png">

This visual has a strange label on the bottom--please remove-- it has a location at the bottom but I am not using a filter - please ensure this is correct.

**Comment by Mellorison** [comment]
It is actually a combination of two tables. Side by side bars as requested in the Dashboard checklist document. The "strange" label must be the an error in the naming of the data in the database. Will look into it right away.

**Comment by Mellorison** [comment]
Resolved.
