### ISSUE TITLE
DHS tables should not show value or count it should only say percentage 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#551]
<img width="810" alt="screen shot 2018-11-15 at 11 30 23 am" src="https://user-images.githubusercontent.com/38062748/48543315-ec941b80-e8c9-11e8-9b3f-6dbcf1bdfad7.png">

A number of these charts are like this- please apply and correct all. It should only have percentage.

**Comment by Mellorison** [comment]
Resolved.
