### ISSUE TITLE
The Big Numbers

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#552]
what time period are the Big numbers looking at is it per Quarter or are they an aggregate of all quarters

**Comment by nsoko** [comment]
I would suggest the big number shows per quarter

**Comment by Mellorison** [comment]
Which Big Number visuals are you referring to specifically?

**Comment by nsoko** [comment]
All the Big Numbers  they should be show data per quarter  probably we need to set a default time period which should reflect so
