### ISSUE TITLE
Quarters seem to be incorrectly labeled? 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#554]
<img width="898" alt="screen shot 2018-11-15 at 11 59 17 am" src="https://user-images.githubusercontent.com/38062748/48545170-f3249200-e8cd-11e8-8a52-641e93b9408a.png">

This chart jumps between 2017 data and 2018 data...not sure if it is because the labels are incorrect ...please correct. Again- should only be displaying 2018 data.

**Comment by AndreLesa** [comment]
2017 data filtered out.
