### ISSUE TITLE
ALL DHS charts should follow the same ordering of Provinces for BOTH males and females so that it is standardized

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#555]
<img width="899" alt="screen shot 2018-11-15 at 12 11 22 pm" src="https://user-images.githubusercontent.com/38062748/48545919-ab9f0580-e8cf-11e8-85ff-1f7ccb4a62d9.png">

Please make sure all DHS charts are in the same order (ideally how they appear in the DHS) for both male and female charts

**Comment by Mellorison** [comment]
Resolved.
