### ISSUE TITLE
Fix ordering of provinces in youth DHS charts + show percentage not value and remove search feature

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#556]
<img width="622" alt="screen shot 2018-11-15 at 12 22 24 pm" src="https://user-images.githubusercontent.com/38062748/48546493-2e749000-e8d1-11e8-9b9e-c1ec17cf7326.png">

Should follow same standardized order as the male / female charts. 

Also should not show count or value but rather percentage AND eliminate the search feature

**Comment by Mellorison** [comment]
Resolved.
