### ISSUE TITLE
Stakeholder directory: Validate organization name field to only allow alphanumeric characters

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/nacmis#56]
- Must not allow users to enter ALL numbers as name of the organization

- However, it should be able to allow characters such as hyphens but they must be accompanied by at least one letter

![gitshot1](https://user-images.githubusercontent.com/25362528/39421564-e76db0be-4c69-11e8-982b-353a89af09c9.PNG)

**Comment by kaykabwe** [comment]
Resolved! under issue #241
