### ISSUE TITLE
Filtering by organisation using parent organisation 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#560]
we have not seen this feature  function 
how do we filter by organisation using the parent organisation

**Comment by Mellorison** [comment]
The following is the status of the Filters:
- Female/male : Can not be implemented.
- Age Disaggregation can not be implemented
- Timestamp : Implemented
- Classification type(organization) : Implemented on the Map
- Target Group : Implemented
- Geographic activities : Implemented on Map
- Province/District/Ward By  organization (show breakdown of who is working where and doing what) : Implemented on Map
