### ISSUE TITLE
Visuals pulling from wrong place in key pops? 

### ISSUE THREAD

**Issue by eefronson** [BlueCodeSystems/nacmis#562]
The visual on inmates and the one persons with disabilities on the SARF they aren't disaggregated by age-- so don't think these can be correct in the system??

<img width="590" alt="screen shot 2018-11-18 at 8 22 18 pm" src="https://user-images.githubusercontent.com/38062748/48676445-cee7e000-eb6f-11e8-8e8f-bc6eea23cd19.png">
<img width="590" alt="screen shot 2018-11-18 at 8 22 18 pm" src="https://user-images.githubusercontent.com/38062748/48676452-d909de80-eb6f-11e8-8e49-e63a5868c337.png">

**Comment by Mellorison** [comment]
Resolved.
