### ISSUE TITLE
Indicator on diablity is pulling from a wrong source 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#570]
![image](https://user-images.githubusercontent.com/38098694/48999642-ee7a9c00-f15f-11e8-8aec-c3f7aca168d8.png)

the disability indicator does not breakdown by age categories

**Comment by Mellorison** [comment]
<img width="380" alt="disability" src="https://user-images.githubusercontent.com/41048336/49054911-8b8c1200-f1fe-11e8-8d03-7e467e545003.PNG">
<img width="874" alt="pwd" src="https://user-images.githubusercontent.com/41048336/49054922-90e95c80-f1fe-11e8-81ca-fe4e86be5928.PNG">
I have changed the disability indicator to breakdown by province as requested in the desired visualization Checklist. Is this okay?

**Comment by Mellorison** [comment]
This should be resolved. Kindly confirm.

**Comment by Mellorison** [comment]
Resolved.
