### ISSUE TITLE
Validation: Disallow entry of future dates

### ISSUE THREAD

**Issue by AndreLesa** [BlueCodeSystems/nacmis#58]

**Comment by kaykabwe** [comment]
Split to two tasks. 

- [ ] Make date picker only select years. To revisit solution to this
- [ ] Either use model forms or override predefined functions.

**Comment by NanaPietrausT** [comment]
still allowing future dates

**Comment by kaykabwe** [comment]
HTML5 has no provision to select year only.

**Comment by AndreLesa** [comment]
Closed in reference to #124
