### ISSUE TITLE
Error appears when trying to Save user dacalunte

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#582]
![image](https://user-images.githubusercontent.com/38098694/52843528-12200380-310b-11e9-8722-81dbdb0cf068.png)

**Comment by kaykabwe** [comment]
@nsoko make sure the national organisation, province and district are set. its probably coming from there.

**Comment by nsoko** [comment]
they are set and that is what is happenning

**Comment by kaykabwe** [comment]
ok. will check

**Comment by nsoko** [comment]
its supposed to provide some useful feed  instead of the error

**Comment by nsoko** [comment]
how far with this Lunte issue

**Comment by kaykabwe** [comment]
@nsoko  dacalunte is working and can be edited. Will keep this issue open in the meantime. Also will work on more meaningful errors
