### ISSUE TITLE
HMIS indicators not filtering to province & districts on showing national figure

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#583]
![image](https://user-images.githubusercontent.com/38098694/52844532-72b04000-310d-11e9-916f-4172598f34c5.png)

**Comment by Mellorison** [comment]
Will look into this as soon as possible..

**Comment by nsoko** [comment]
how far with this issue

**Comment by Mellorison** [comment]
Sorry for the delay. This should be resolved. Kindly check to ascertain this.

**Comment by Mellorison** [comment]
Kindly re-open if issue still persists.
