### ISSUE TITLE
error in Editing an existing SARF dacansama account 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#585]
![image](https://user-images.githubusercontent.com/38098694/53167589-0176fe00-35e1-11e9-985f-a0b9f3ba486f.png)

we are trying to editing SARF that was entered some time back 
using the dacansama account it is giving an error 
however using my super admin account things appear normal 
please assist

**Comment by kaykabwe** [comment]
Good morning @nsoko , try checking if its still doing the same.
link to the form: https://nacmis.org.zm/admin/data_entry/activityreportform/826/change/

**Comment by nsoko** [comment]
its still doing the same  this happens when u are logged in using data account 
username: dacansama
password:nacmis100%

**Comment by kaykabwe** [comment]
okay. I see.

**Comment by kaykabwe** [comment]
Resolved
