### ISSUE TITLE
Indicator on condom distribution ponits shows zero 

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#587]
![image](https://user-images.githubusercontent.com/38098694/53236374-c89c5f00-369c-11e9-84e8-199d0e3710bc.png)

Indicator on condom distribution ponits shows zero  in spite of  the  fact that data has been entered on this indicator 
kindly assist

**Comment by Mellorison** [comment]
Resolved. Kindly Refresh/Reload your Dashboard browser page.

**Comment by nsoko** [comment]
This is not still working properly   its only filtering for copperbelt the    rest of the provinces are showing zeros kindly revisit

**Comment by Mellorison** [comment]
This should be working now. Kindly check to ascertain this.

**Comment by Mellorison** [comment]
Kindly re-open if issue still persists.

**Comment by nsoko** [comment]
it working now thanks
