### ISSUE TITLE
when logged in as PITMEO only parent organisation shows  

### ISSUE THREAD

**Issue by nsoko** [BlueCodeSystems/nacmis#589]
![image](https://user-images.githubusercontent.com/38098694/54416981-95804500-4709-11e9-9009-f020d427372b.png)

**Comment by kaykabwe** [comment]
As a superuser, login to NACMIS. click the following sequence once on the site administration side. Click Groups -> PITMEO -> Select Permissions in the left column, Use middle arrow to move to right,

For now, I have given PITMEO permission to view organizations. You will have to select these permissions regarding to what NAC wants a PITMEO to be able to see.

**Comment by nsoko** [comment]
Noted thanks
