### ISSUE TITLE
Make dropdowns searchable

### ISSUE THREAD

**Issue by AndreLesa** [BlueCodeSystems/nacmis#62]
Probably related to #61 

Look at this: https://github.com/applegrew/django-select2

It might solve all the dropdown related issues.

**Comment by kaykabwe** [comment]
form can add multiple widgets on but gives error on save
![screenshot from 2018-05-10 16-30-10](https://user-images.githubusercontent.com/33322655/39874937-84999206-546f-11e8-8666-09b11da33355.png)

**Comment by AndreLesa** [comment]
Are the lists being generated from the tuples or it's somewhere else?
