### ISSUE TITLE
Update the address field to clarify that a DISTRICT office is being requested

### ISSUE THREAD

**Issue by AndreLesa** [BlueCodeSystems/nacmis#73]
Update the address field to clarify that a DISTRICT office is being requested. Consider how to guide stakeholders that may not have a district office even if they have activities in the district. (Example- utilize the next highest office?)

**Comment by kaykabwe** [comment]
@AndreLesa Just a little more classification. Would this mean I also make this not required too?

**Comment by kaykabwe** [comment]
![screenshot from 2018-05-08 11-15-50](https://user-images.githubusercontent.com/33322655/39748786-5045543c-52b1-11e8-9f54-14967c84fd61.png)

**Comment by kaykabwe** [comment]
Solved and waiting on review.
