### ISSUE TITLE
Activity report form: Error on opening page

### ISSUE THREAD

**Issue by bjlarkin** [BlueCodeSystems/nacmis#85]
Hi BlueCode! 

When attempting to click on 'add' or 'activity report form', I am receiving a programming error (screen shot is attached). Is this a bug or is the page under construction? 

I am hoping to do a guided feedback session on this form with Akros staff this week. 

Thank you for the help! 
<img width="1440" alt="screen shot 2018-05-07 at 09 46 41" src="https://user-images.githubusercontent.com/38097551/39690899-f2fd7c94-51db-11e8-8091-399a244191b6.png">

Bethany

**Comment by tobiasmakai** [comment]
Hi Bethany, thanks for flagging this issue.
The issue is on the server side and will be rectified soon.

**Comment by kaykabwe** [comment]
Issue rectified.
