### ISSUE TITLE
Stakeholder Activity Form- Error on saving form

### ISSUE THREAD

**Issue by bjlarkin** [BlueCodeSystems/nacmis#97]
Hi BlueCode! 

There appears to be an error on the SARF form when users hit 'Save and close' or 'Save and add other'. Please see PDF error report attached.

Thank you!
[NACMIS error.pdf](https://github.com/BlueCodeSystems/nacmis/files/1994634/NACMIS.error.pdf)

Bethany

**Comment by kaykabwe** [comment]
@bjlarkin May may kindly test again as that issue was already fixed.

**Comment by bjlarkin** [comment]
@kaykabwe - just checked! Appears to be working today - thank you! 👍
